// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
	metav1 "k8s.io/client-go/applyconfigurations/meta/v1"
)

// CatStatusApplyConfiguration represents a declarative configuration of the CatStatus type for use
// with apply.
type CatStatusApplyConfiguration struct {
	Conditions []metav1.ConditionApplyConfiguration `json:"conditions,omitempty"`
}

// CatStatusApplyConfiguration constructs a declarative configuration of the CatStatus type for use with
// apply.
func CatStatus() *CatStatusApplyConfiguration {
	return &CatStatusApplyConfiguration{}
}

// WithConditions adds the given value to the Conditions field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Conditions field.
func (b *CatStatusApplyConfiguration) WithConditions(values ...*metav1.ConditionApplyConfiguration) *CatStatusApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithConditions")
		}
		b.Conditions = append(b.Conditions, *values[i])
	}
	return b
}
